// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqusugwosguaabbaliju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxdXN1Z3dvc2d1YWFiYmFsaWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDI2NTAsImV4cCI6MjA2ODIxODY1MH0.DjFjv2la9vUmFN2hNIzrJ-1G6FrE4g-wEFOkM-_LXOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});